# Generated by Django 4.0.8 on 2022-12-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
