# Generated by Django 4.0.8 on 2022-12-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_recipe_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Comment',
            field=models.TextField(blank=True),
        ),
    ]
