# Generated by Django 4.0.9 on 2023-02-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_recipe_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
